# Generated by Django 5.2.10 on 2026-01-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_is_completed_task_description_and_more'),
        ('tasks', '0004_initial_categories'),
    ]

    operations = [
    ]
